version: "3.3"

services:
  force:
    build: ./app
    container_name: force
    volumes:
      - /home/matheus/:/credentials
      - /home/matheus/Codigos/force/app/metadata/:/metadata
      - /home/matheus/Codigos/force/app/lista/:/lista
      - /home/matheus/Codigos/force/app/shapefile/:/shapefile
    environment:
      - BOTO_CONFIG=/credentials/.boto
