version: "3.3"

services:
  force:
    build: ./force
    container_name: force
    volumes:
      - /home/matheus/:/credentials
      - /docker/volumes/force/metadata/:/metadata
      - /docker/volumes/force/lista/:/lista
    environment:
      - BOTO_CONFIG=/credentials/.boto
